// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: proto/application.proto

package application

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User hits the server and asks for a show recommendation.
// This is the PB message to be received by our service.
type ShowRecommendationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ShowRecommendationRequest) Reset() {
	*x = ShowRecommendationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_application_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowRecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowRecommendationRequest) ProtoMessage() {}

func (x *ShowRecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowRecommendationRequest.ProtoReflect.Descriptor instead.
func (*ShowRecommendationRequest) Descriptor() ([]byte, []int) {
	return file_proto_application_proto_rawDescGZIP(), []int{0}
}

func (x *ShowRecommendationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// A show recommendation message which contains the name of the
// individual that requested the recommendation, and the name of
// the show that is being recommended.
// This is the PB message to be returned by our service.
type ShowRecommendation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Show string `protobuf:"bytes,2,opt,name=show,proto3" json:"show,omitempty"`
}

func (x *ShowRecommendation) Reset() {
	*x = ShowRecommendation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_application_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowRecommendation) ProtoMessage() {}

func (x *ShowRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowRecommendation.ProtoReflect.Descriptor instead.
func (*ShowRecommendation) Descriptor() ([]byte, []int) {
	return file_proto_application_proto_rawDescGZIP(), []int{1}
}

func (x *ShowRecommendation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShowRecommendation) GetShow() string {
	if x != nil {
		return x.Show
	}
	return ""
}

var File_proto_application_proto protoreflect.FileDescriptor

var file_proto_application_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x19, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x77, 0x52,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x68, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x68, 0x6f, 0x77, 0x32, 0x77, 0x0a, 0x19, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x5a, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x53,
	0x68, 0x6f, 0x77, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x42, 0x0f,
	0x5a, 0x0d, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_application_proto_rawDescOnce sync.Once
	file_proto_application_proto_rawDescData = file_proto_application_proto_rawDesc
)

func file_proto_application_proto_rawDescGZIP() []byte {
	file_proto_application_proto_rawDescOnce.Do(func() {
		file_proto_application_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_application_proto_rawDescData)
	})
	return file_proto_application_proto_rawDescData
}

var file_proto_application_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_application_proto_goTypes = []interface{}{
	(*ShowRecommendationRequest)(nil), // 0: application.ShowRecommendationRequest
	(*ShowRecommendation)(nil),        // 1: application.ShowRecommendation
}
var file_proto_application_proto_depIdxs = []int32{
	0, // 0: application.ShowRecommendationService.RecommendShow:input_type -> application.ShowRecommendationRequest
	1, // 1: application.ShowRecommendationService.RecommendShow:output_type -> application.ShowRecommendation
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_application_proto_init() }
func file_proto_application_proto_init() {
	if File_proto_application_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_application_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowRecommendationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_application_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowRecommendation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_application_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_application_proto_goTypes,
		DependencyIndexes: file_proto_application_proto_depIdxs,
		MessageInfos:      file_proto_application_proto_msgTypes,
	}.Build()
	File_proto_application_proto = out.File
	file_proto_application_proto_rawDesc = nil
	file_proto_application_proto_goTypes = nil
	file_proto_application_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShowRecommendationServiceClient is the client API for ShowRecommendationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShowRecommendationServiceClient interface {
	RecommendShow(ctx context.Context, in *ShowRecommendationRequest, opts ...grpc.CallOption) (*ShowRecommendation, error)
}

type showRecommendationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShowRecommendationServiceClient(cc grpc.ClientConnInterface) ShowRecommendationServiceClient {
	return &showRecommendationServiceClient{cc}
}

func (c *showRecommendationServiceClient) RecommendShow(ctx context.Context, in *ShowRecommendationRequest, opts ...grpc.CallOption) (*ShowRecommendation, error) {
	out := new(ShowRecommendation)
	err := c.cc.Invoke(ctx, "/application.ShowRecommendationService/RecommendShow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShowRecommendationServiceServer is the server API for ShowRecommendationService service.
type ShowRecommendationServiceServer interface {
	RecommendShow(context.Context, *ShowRecommendationRequest) (*ShowRecommendation, error)
}

// UnimplementedShowRecommendationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShowRecommendationServiceServer struct {
}

func (*UnimplementedShowRecommendationServiceServer) RecommendShow(context.Context, *ShowRecommendationRequest) (*ShowRecommendation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecommendShow not implemented")
}

func RegisterShowRecommendationServiceServer(s *grpc.Server, srv ShowRecommendationServiceServer) {
	s.RegisterService(&_ShowRecommendationService_serviceDesc, srv)
}

func _ShowRecommendationService_RecommendShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowRecommendationServiceServer).RecommendShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/application.ShowRecommendationService/RecommendShow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowRecommendationServiceServer).RecommendShow(ctx, req.(*ShowRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShowRecommendationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "application.ShowRecommendationService",
	HandlerType: (*ShowRecommendationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecommendShow",
			Handler:    _ShowRecommendationService_RecommendShow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/application.proto",
}
